### ISSUE TITLE
[CHANGE] Mark duckstation as proprietary software

### ISSUE THREAD

**Issue by RemasteredArch** [abUwUser/beyond-software-list#16]
**Which entry should be changed?**
Inform which entry has issues
> [duckstation](https://github.com/stenzek/duckstation/)

**What's wrong with?**
Provide a clear and cohesive description on what it lacks
> No longer considered open source software after changing to a proprietary license

**What changes should be applied**
Provide what changes we need to make
> mark it as proprietary

**Additional Notes**
Since commit [`7690675`](https://github.com/stenzek/duckstation/commit/76906756d0b5f93ac2559c29676cbea11496a21a), duckstation has been licensed under the terms of [`CC-BY-NC-ND-4.0`](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en), which does not meet the [Open Source Definition](https://opensource.org/osd). This makes it _source available_ software, but that still matches for an icon called `:c-proprietary:`.

Cheers!

**Comment by resucutie** [comment]
I have to be honest, on a second thought I should rename the `:c-proprietary:` tag to closed source instead of just proprietary. My intention with the tag was to show that the model does not respect any standard of "open collaborative work" AND "trust on the code level", and as such if you're going to use it, you may be in danger of having to change to a completely new software due to anti-user actions that the owners may take and due to invasive changes that you cannot check on the codebase.

Althoguh it does not meet the OSD, it also does not meet the standard of "I have no way to trust this software". The code is source avaiable, so you can trust on what the code does at least.

But, if you can suggest a fork of DuckStation that uses a FOSS license, please lmk
